review frontend
commune-ai/frontend pull request #78
Opened 2024-03-13 18:25 UTC by cdreamer1

2024-03-13 20:41 UTC, hi-zeus requested changes
@cdreamer1 
- It would be better if you added types for hooks.
- Remove unnecessary code completely. (not comment)

Thanks

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/settings/profile/page.tsx
>                          Items.map((item, index) => {
Use camel case.

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/workSpace/@details/[...moduleName]/components/module-details-modal/module-details-modal.tsx
- Fix the file structure (using Atomic design structure)
- Move the components files in to components directory. (atoms, molecules, organisms, templates)

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/workSpace/CustomNode.tsx
- Fix the file structure (using Atomic design structure)
- Move the components files in to components directory. (atoms, molecules, organisms, templates)

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/workSpace/components/module-item/index.tsx
- Fix the file structure (using Atomic design structure)
- Move the components files in to components directory. (atoms, molecules, organisms, templates)

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/workSpace/components/module-tile/module-tile.tsx
- Fix the file structure (using Atomic design structure)
- Move the components files in to components directory. (atoms, molecules, organisms, templates)

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/app/workSpace/components/search-bar.tsx
- Fix the file structure (using Atomic design structure)
- Move the components files in to components directory. (atoms, molecules, organisms, templates)

2024-03-13 20:41 UTC, hi-zeus commented on frontend/src/components/substrate.component.tsx
Move in to directory.

2024-03-13 23:00 UTC, merged

2024-03-14 19:42 UTC, hi-zeus commented
@Tunki1201  
If you merge code without checking the modifications after a code review, a review is not necessary.

2024-03-14 22:02 UTC, Tunki1201 commented
Yes, I am.
Did not you also review the code?

On Thu, Mar 14, 2024 at 3:43 PM hi ***@***.***> wrote:

> @Tunki1201 <https://github.com/Tunki1201>
> If you merge code without checking the modifications after a code review,
> a review is not necessary.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/commune-ai/frontend/pull/78#issuecomment-1998299078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BANS54GZXIN7DPAH6KKN3BLYYH4U7AVCNFSM6AAAAABEUWC4PCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJYGI4TSMBXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-15 14:13 UTC, cdreamer1 commented on frontend/src/app/settings/profile/page.tsx
>                          Items.map((item, index) => {
changed Items to items.

2024-03-15 15:39 UTC, cdreamer1 commented on frontend/src/components/substrate.component.tsx
Moved this component into components/atoms/button directory.

2024-03-15 16:24 UTC, cdreamer1 commented on frontend/src/app/workSpace/components/module-item/index.tsx
Moved this component into the workspace/components/molecules/ directory.

2024-03-15 16:25 UTC, cdreamer1 commented on frontend/src/app/workSpace/components/module-tile/module-tile.tsx
Moved this component into the workspace/components/molecules/ directory.

2024-03-15 19:27 UTC, cdreamer1 commented on frontend/src/app/workSpace/CustomNode.tsx
Moved this component into workspace/components/organisms/ directory.

2024-03-15 20:29 UTC, hi-zeus commented
@Tunki1201 
After review,  you have to check the fix result.
After confirm, then you can merge it.

2024-03-15 21:46 UTC, Tunki1201 commented
ok, got it

On Fri, Mar 15, 2024 at 4:29 PM hi ***@***.***> wrote:

> @Tunki1201 <https://github.com/Tunki1201>
> After review, you have to check the fix result.
> After confirm, then you can merge it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/commune-ai/frontend/pull/78#issuecomment-2000398794>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BANS54CP2YMSJIJTVJLR2ULYYNK3LAVCNFSM6AAAAABEUWC4PCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBQGM4TQNZZGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>